/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/9.4.8.v20171121
 * Generated at: 2018-01-05 05:49:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.io.*;
import com.netflix.eureka.*;
import com.netflix.eureka.registry.*;
import com.netflix.eureka.util.*;
import com.netflix.discovery.shared.Pair;

public final class lastN_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("com.netflix.eureka.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.netflix.eureka");
    _jspx_imports_packages.add("com.netflix.eureka.registry");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.netflix.discovery.shared.Pair");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://"
            + request.getServerName() + ":" + request.getServerPort()
            + path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("    <title>Eureka - Last N events</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./css/main.css\">\r\n");
      out.write("    <link type=\"text/css\" href=\"./css/jquery-ui-1.7.2.custom.css\" rel=\"Stylesheet\" />\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery-1.11.1.js\" ></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery-ui-1.7.2.custom.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" >\r\n");
      out.write("       $(document).ready(function() {\r\n");
      out.write("           $('table.stripeable tr:odd').addClass('odd');\r\n");
      out.write("           $('table.stripeable tr:even').addClass('even');\r\n");
      out.write("           $(\"#tabs\").tabs();\r\n");
      out.write("           });\r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body id=\"three\">\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write("\r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("\t<div id=\"tabs\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t    <li><a href=\"#tabs-1\">Last 1000 canceled leases</a></li>\r\n");
      out.write("\t    <li><a href=\"#tabs-2\">Last 1000 newly registered leases</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("    <div id=\"tabs-1\">\r\n");
      out.write("      ");

      EurekaServerContext serverContext = (EurekaServerContext) pageContext.getServletContext()
              .getAttribute(EurekaServerContext.class.getName());
      PeerAwareInstanceRegistry registry = serverContext.getRegistry();
      List<Pair<Long, String>> list = registry.getLastNCanceledInstances();
      out.print("<table id=\'lastNCanceled\' class=\"stripeable\">");
      out.print("<tr><th>Timestamp</th><th>Lease</th></tr>");
      for (Pair<Long, String> entry : list) {
          out.print("<tr><td>" + (new Date(entry.first().longValue()))
                  + "</td><td>" + entry.second() + "</td></tr>");
      }
      out.println("</table>");
     
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"tabs-2\">\r\n");
      out.write("      ");

      list = registry.getLastNRegisteredInstances();
      out.print("<table id=\'lastNRegistered\' class=\"stripeable\">");
      out.print("<tr><th>Timestamp</th><th>Lease</th></tr>");
      for (Pair<Long, String> entry : list) {
          out.print("<tr><td>" + (new Date(entry.first().longValue()))
                  + "</td><td>" + entry.second() + "</td></tr>");
      }
      out.println("</table>");
     
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
